### ISSUE TITLE
Animated GIF support

### ISSUE THREAD

**Issue by Niek** [jerch/node-sixel#19]
Would it be possible to support animated GIFs? When I try to show a GIF with `img2sixel.js` I see the first frame only. Loading the GIF with `img2sixel` from libsixel works fine.

**Comment by jerch** [comment]
Possible - yes, but not useful for this project. This lib deals with the low level conversion of images given as pixel data to a sixel image.

But you can do it yourself - grab a GIF converter outputting single image frames as pixel data, convert them to sixel images, and write them with a timing constraint to the terminal (with cursor reset in between to overwrite the previous image).

Note that `image2sixel.js` is just a quick showcase, not much use to extend it that way (just use `img2sixel` for that).

**Comment by Niek** [comment]
That makes sense, thanks for the reply. Closing this issue.
