### ISSUE TITLE
is using a TransitionTable worth it?

### ISSUE THREAD

**Issue by PerBothner** [jerch/node-sixel#2]
This is partly a personal preference, but it seems to me that hard-coded logic with switch statements would be a lot easier to understand, maintain, more compact, and probably more efficient than using a TransitionTable.  A table makes sense when the bindings may change or be settable, but I don't think that applies for parsing sixel data - I doubt any addon is going to be extending or modifying the format.

On the other hand, the TransitionTable logic is already written, and (presumably) works, so if it ain't broke ...

**Comment by jerch** [comment]
I actually started with if/else parsing which was ~30% slower, and the code being 2 times as long with some repetitions. Thus yeah works with the transition table quite nice. and is more compact.

**Comment by PerBothner** [comment]
Cool. I'll close my suggestion.
