### ISSUE TITLE
working code for DomTerm

### ISSUE THREAD

**Issue by PerBothner** [jerch/node-sixel#6]
This is not so much an issue as a report that I managed to use node-sixel to "print" sixel data in DomTerm. The interesting part of the new code is:

        let six = new SixelImage();
        six.writeString(text, 1);
        let w = six.width, h = six.height;
        const sarray = new Uint8ClampedArray(4 * w * h);
        six.toImageData(sarray, w, h);
        const idata = new ImageData(sarray, w, h);
        const canvas = document.createElement("canvas");
        canvas.setAttribute("width", w);
        canvas.setAttribute("height", h);
        const ctx = canvas.getContext('2d');
        ctx.putImageData(idata, 0, 0);
        if (true) {
            // This works better with "Save as HTML"
            let image = new Image(w, h);
            image.src = canvas.toDataURL();
            this.insertNode(image);
        } else {
            this.insertNode(canvas);
        }

If you see a cleaner/better way to do it, I'd welcome any advice.  (These APIs are very new to me.)

The DomTerm code needs more testing and work.  For example using libsixel to "printf" an animated gif isn't working.

(I got very frustrated trying to import the compiled lib/index.js into DomTerm.  I finally converted DomTerm to es6 modules, and that worked.  Using es6 modules seems like a good thing to do regardless - though there are still some rough spots.)

**Comment by jerch** [comment]
@PerBothner I think the ctor `new ImageData(...)` is not supported everywhere (IE, Safari?) while `createImageData()` or `getImageData()` seem to work on all major browsers.

**Comment by PerBothner** [comment]
Thanks.  My current version is this:

        let six = new SixelImage();
        six.writeString(text, 1);
        let w = six.width, h = six.height;
        const canvas = document.createElement("canvas");
        canvas.setAttribute("width", w);
        canvas.setAttribute("height", h);
        const ctx = canvas.getContext('2d');
        const idata = ctx.createImageData(w, h);
        six.toImageData(idata.data, w, h);
        ctx.putImageData(idata, 0, 0);
        if (true) {
            // This works better with "Save as HTML"
            let image = new Image(w, h);
            image.src = canvas.toDataURL();
            this.insertNode(image);
        } else {
            this.insertNode(canvas);
        }

**Comment by jerch** [comment]
Yeah I think there is no way around a canvas to get the image converted into a png or jpg (unless you want to do it the hard way and do it yourself in javascript).
If you see a chance to get byte data from the other side instead of a string, I suggest to switch to `write`. If you have to rely on string data you might want to try if doing `charCodeAt` in `write` works better than doing it beforehand explicitly.

**Comment by PerBothner** [comment]
_"Also about gifs: as far as I can see, libsixel seems to exit sixel state, repositions the text cursor and overdraws the old picture."_

That is my understanding, too.  I just haven't tried debugging animated gifs yet.  I'm not sure we want to worry too much about enhancing SixelImage to handle updating, rather than just handling the brute-force way libsixel re-draws things.  Given that sixel is such a crappy format, I think just re-creating and re-drawing is good enough.

I think it would be useful to have an addon API where an application can send an escape sequence to allocate a canvas, and then send escape sequences to draw into the canvas.  I haven't looked at the Regis command set; I suspect others have had a similar idea. It would also be interesting to be able to animate and update SVG images.

**Comment by jerch** [comment]
> ... I think just re-creating and re-drawing is good enough.

Yeah agreed, this old format is not worth to invest to much time at all. I also think libsixel tried to be smart here and updates only pixels that were changed, but my xterm version (ubuntu 16) seems not to handle it correctly and blacks out the sixel area first losing the unchanged pixel info.

> I think it would be useful to have an addon API where an application can send an escape sequence to allocate a canvas, and then send escape sequences to draw into the canvas.

Yeah I think thats basically what REGIS does. But REGIS support? Idk, the format seems way more complicated and I am not aware of any halfway modern app supporting it. And we have with svg a much more modern alternative.
Drawing svg to canvas - you mean like a painter thingy that can translate svg commands into primitives like brushes and draw shapes?

**Comment by jerch** [comment]
Ah ok. Well to animate things on that SVG, javascript is there for the rescue (I think most browsers support JS in SVGs). Only problem I see here might be security - not sure if its possible to lock down those JS snippets in way that they never will be able to reach xterm.js' state.

The second idea pretty much sounds like a REGIS impl with browser tools, but with a json "protocol". Not sure if REGIS is worth a look, might be to limited for modern vector ideas. Idk. Btw gnuplot has even REGIS support, haha. Guess gnuplot can even draw to a physical wandboard :smile:

**Comment by PerBothner** [comment]
_"Well to animate things on that SVG, javascript is there for the rescue (I think most browsers support JS in SVGs). Only problem I see here might be security - not sure if its possible to lock down those JS snippets in way that they never will be able to reach xterm.js' state."_

I didn't mean to allow downloading JavaScript (though one could).  Rather one could download HTML fragments to replace existing parts of the SVG DOM tree.  The HTML would be sanitized (by default no JavaScript), and you would only be able to replace parts of the DOM that are marked as being replaceable (perhaps require a special `class`, in addition to a suitable `id`).

**Comment by jerch** [comment]
Yes this sounds more feasible from the security perspective, though not sure if one can easily forbid JS execution in SVG snippets. How you gonna deal with foreign resources like outside links and embedded images? (Not sure if tracking is a concern for you.)

**Comment by PerBothner** [comment]
I got animated gifs (`libsixel/images/seq2gif.gif`) working on DomTerm.  I had to fix some issues with cursor positioning and character deletion. The concept is that the `<img>` element counts as a single character cell in the grid (regardless of its size).  More generally, this applies to "object elements', which are currently `<object>`, `<img>`, `<svg>`, and `<iframe>`. As a cheat, I do an "erase-line-right" (delete all characters and object elements to the right of the cursor position) before inserting the `<img>`.  (It might be conceptually cleaner and more consistent for a new '<img>` to "overwrite" the next cell, but this is simpler.)

A mix of text and images also works.  For example:

    echo -n 'foo' && cat map8.six && echo -n bar

This prints the `bar` to the right of and on the same line as the image.  However, this does not match xterm. Arguably, xterm is wrong, since map8.six does not end with a graphics new-line command.  If my interpretation is correct, we should enhance node-sixel with a boolean to indicate if there was a final sixel new-line.  It would be nice to verify what is the correct behavious.

**Comment by jerch** [comment]
Yeah its kinda hard to grasp the "correct handling" since mlterm and xterm kinda differ in some ways. I also had issues to compare different xterm versions, they also behave slightly different. 
Btw xterm has another setting regarding sixels: `CSI ? 8452 h` which enables the cursor to stick the text cursor in the next cell and not to wrap into the next line.

I think node-sixel currently just ignores NLs at the end (the parser only creates bands if there is "realised" content written to it). Maybe this is wrong? Furthermore if the sixel data contain a width/height token `SixelImage` reports these settings as width/height, even if the bands ended earlier/later (both in length or amount).

**Comment by jerch** [comment]
Edit: I think there are more awkwardities hidden - imho the palette handling should be terminal wide by default, not sure yet if changes to this palette would also affect older images. If thats the case the whole library needs to be rewritten. :-1:

**Comment by PerBothner** [comment]
_"If thats the case the whole library needs to be rewritten."_

Why can't we just re-use the `SixelImage` object for successive images?

**Comment by jerch** [comment]
> Why can't we just re-use the SixelImage object for successive images?

Yes we could, but it would not solve the problem that a later change to a palette color might affect older images. For this to take place we would have to either swap pixel colors from old to new color, or change the way a band stores the data (maybe store single sixel band data per palette entry and apply the color values later in `toImageData`). I dont like it, it just feels wrong, but I think the current palette handling is not compatible with real idea behind it.

**Comment by PerBothner** [comment]
Have you verified that on xterm (and mlterm?) if you change the palette it changes previous images?

Regardless, there is a point of diminishing returns in attempting fidelity to an obsolete standard. Unless someone has an application that depends on palette updating, I think you should be satisfied with the current design. You can always revisit it later.

**Comment by jerch** [comment]
Offtopic:
Btw OpenVMS is currently ported to x86. Weird to see that many corps that were highly invested into DEC/alpha in the 90s still run business critical stuff on this OS 25ys later.

**Comment by jerch** [comment]
Closing this issue as there are no sixel related things open.
