### ISSUE TITLE
terminals supported and node working example?

### ISSUE THREAD

**Issue by cancerberoSgx** [jerch/node-sixel#9]
This project seems awesome but in my case I need to run it in node. Tried in max and linux to run ''sixel_textcursor.sh" and variations but I think it does not work. I think making it work in node add the real value here...  Which terminals can I use to  make it work ? Or should I use node-canvas and simulate a project (which I would avoid for performance=?) (I have some experience with tput and terminal). Thanks, keep it up

**Comment by jerch** [comment]
@cancerberoSgx 
Not sure if you mixed up a few things here. `sixel_textcursor.sh` is not needed to work with this lib, its just a dev helper script I needed to get the right cursor handling done. It will only work in terminals supporting sixel output (xterm with vt340 flag or mlterm).

The lib does not care for image formats like png or jpeg, it spits out raw RGBA bytes instead. Thus you gonna need some abstraction to work with raw image bytes. The example shows how this can be done with the canvas in browser:

https://github.com/jerch/node-sixel/blob/852fc507d1b0ff18bab3b42f79ea6326fbbabccc/index.html#L62-L82

You can either use `node-canvas` to do it likewise or use some other RGBA to png/jpeg lib.

**Comment by cancerberoSgx** [comment]
Oh yes so I got confused, so the missing part for me is testing with those terminals that I assume are the only known supported?. Ok, Could you please not close the issue well I try to document a small working example using the lib with node ? (perhaps reproducing the browser example in node?) thanks

**Comment by jerch** [comment]
> Oh yes so I got confused, so the missing part for me is testing with those terminals that I assume are the only known supported?.

Those are 2 commonly found terminal emulators that support SIXEL. @PerBothner recently also added SIXEL support to [DomTerm](https://github.com/PerBothner/DomTerm).

> Ok, Could you please not close the issue well I try to document a small working example using the lib with node ? (perhaps reproducing the browser example in node?) thanks

Still not sure if you got the right idea what this lib can do for you, care to explain? The only use case I see is to convert SIXEL data into image bytes, which is useful if you want to write your own terminal emulator with SIXEL support. There is no "other terminal" involved into this.

**Comment by jerch** [comment]
This a rudimentary example in node to read in SIXEL data and create a png with node-canvas:

```JS
const { SixelImage } = require('./lib/index');
const { createCanvas, createImageData } = require('canvas');
const fs = require('fs');
const open = require('open');

fs.readFile('testfiles/screen_clean.six', (err, data) => {
  // read in sixel data
  const sixelImage = new SixelImage();
  sixelImage.write(data);

  // image metrics
  const width = sixelImage.width;
  const height = sixelImage.height;

  // transfer bitmap data to ImageData object
  const imageData = createImageData(width, height);
  sixelImage.toImageData(imageData.data, width, height);

  // draw ImageData to canvas
  const canvas = createCanvas(width, height);
  const ctx = canvas.getContext('2d');
  ctx.putImageData(imageData, 0, 0);

  // write to some file and show it
  const targetFile = __dirname + '/node_example.png';
  const out = fs.createWriteStream(targetFile);
  const stream = canvas.createPNGStream();
  stream.pipe(out);
  out.on('finish', () => open(targetFile));
})
```

And since `SixelImage.write` works streamlined, you can feed it like this:
```JS
sixelFileStream.on('data', (chunk) => sixelImage.write(chunk));
sixelFileStream.on('end', () => {
  // all loaded, do some work with the image
});
```

**Comment by jerch** [comment]
@cancerberoSgx Since your question was directed to SIXEL output from nodejs - I just added SIXEL encoding, thus you can now create SIXEL data from images in node and output it directly to the terminal.

Gonna close this issue, feel free to reopen if something is missing/unanswered.
